name: CI for Load Balancer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t balancer:latest .

    - name: Run unit tests inside Docker container
      run: docker run --rm balancer:latest go test ./... -v

    - name: Run integration tests inside Docker container
      run: docker run --rm -e INTEGRATION_TEST=1 balancer:latest go test ./integration -v

    - name: Run benchmarks inside Docker container
      run: docker run --rm -e INTEGRATION_TEST=1 balancer:latest go test ./integration -bench=. -benchtime=10x -v
